---
version: '3.4'
services:

  loki:
    container_name: loki
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    
  # loki:
  #   image: grafana/loki:2.4.0
  #   container_name: loki
  #   ports:
  #     - '3100:3100'
  #   volumes:
  #     - ./config/loki.yaml:/etc/config/loki.yaml
  #   entrypoint:
  #     - /usr/bin/loki
  #     - '-config.file=/etc/config/loki.yaml'
    networks:
      - proxy

  promtail:
    image: grafana/promtail:2.4.0
    container_name: promtail
    ports:
      - '9080:9080'
    user: root
    volumes:
      - ./log:/var/log/test
      - /var/log/system.log:/var/log/root/system.log
      - ./config/promtail-local-config.yaml:/etc/config/promtail-local-config.yaml
    entrypoint:
      - /usr/bin/promtail
      - '-config.file=/etc/config/promtail-local-config.yaml'
    networks:
      - proxy

networks:
  proxy:
    external: true