---
server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: all-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: nginxbox
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: homebox
          agent: promtail
          __path__: /home/folder/logs/nginx/*folder      

  - job_name: nginx
    static_configs:
    - targets:
        - localhost
      labels:
        app: nginx
        env: production
        host: homebox
        __path__: /home/folder-www1/logs/nginx/*
    pipeline_stages:
    - match:
        selector: '{job="nginx"}'
        stages:
        - regex:
            # logline example: 127.0.0.1 - - [21/Apr/2020:13:59:45 +0000] "GET /?foo=bar HTTP/1.1" 200 612 "http://example.com/lekkebot.html" "curl/7.58.0"
            expression: '^(?P<host>[\w\.]+) - (?P<user>[^ ]*) \[(?P<timestamp>.*)\] "(?P<method>[^ ]*) (?P<request_url>[^ ]*) (?P<request_http_protocol>[^ ]*)" (?P<status>[\d]+) (?P<bytes_out>[\d]+) "(?P<http_referer>[^"]*)" "(?P<user_agent>[^"]*)"?'
        - labels:
            host:
            method:
            request_url:
            status:
            user_agent:

  - job_name: journal
    journal:
      max_age: 1h
      path: /var/log/journal
      labels:
        job: systemd
        env: production
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          cluster: multipass-cluster
          __path__: /var/lib/docker/containers/*/*log

    # --log-opt tag="{{.Name}}"
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag

      - regex:
          expression: (?P<container_name>(?:[^|]*[^|]))
          source: "tag"

      - labels:
          #tag:
          stream:
          container_name:
