version: "3.0"
services:
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest-exporter
    networks:
      - proxy
    ports:
      - 9798:9798
    restart: unless-stopped

networks:
  proxy:
    external: true
